package:
  name: numpy
  version: "1.6.1"
source:
  fn: numpy-1.6.1.tar.gz
  url: https://pypi.python.org/packages/source/n/numpy/numpy-1.6.1.tar.gz
  md5: 2bce18c08fc4fce461656f0f4dd9103e
requirements:
  build:
    - python
    - atlas
  run:
    - python
test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite
    - numpy.core._dotblas
about:
  home: http://numpy.scipy.org/
  license: BSD
